# Generated by Django 4.2.8 on 2023-12-18 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("draw_names", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drawname",
            name="name",
        ),
    ]
