# Generated by Django 4.2.8 on 2023-12-18 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("draw_names", "0002_remove_drawname_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawname",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
