# Generated by Django 4.2.8 on 2023-12-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("draw_names", "0003_drawname_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawnames",
            name="shuffled",
            field=models.BooleanField(default=False),
        ),
    ]
