# Generated by Django 4.2.8 on 2023-12-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("draw_names", "0004_drawnames_shuffled"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawname",
            name="exclude_participant",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="as_exclude_participants",
                to="draw_names.participant",
            ),
        ),
    ]
