# Generated by Django 4.2.8 on 2023-12-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("draw_names", "0005_drawname_exclude_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawname",
            name="whished_gift",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
