# Generated by Django 4.2.8 on 2023-12-18 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("draw_names", "0006_drawname_whished_gift"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drawname",
            old_name="whished_gift",
            new_name="wished_gift",
        ),
    ]
